channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=24.1
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - jaraco-text==3.12.1
  - numpy==1.22.0
  - ordered-set==4.1.0
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.11.4
name: mlflow-env
